# Bootloader
TARGET_BOOTLOADER_BOARD_NAME :=

# CPU
TARGET_CPU_CORTEX_A53 := true

# WT88047 init
TARGET_LIBINIT_MSM8916_DEFINES_FILE := device/wingtech/wt88047/init/init_wt88047.cpp
TARGET_UNIFIED_DEVICE := true
