# Camera
BOARD_CAMERA_SENSORS := ov2680_5987fhq ov8865_q8v18a ov2680_skuhf
TARGET_USE_VENDOR_CAMERA_EXT := true
USE_DEVICE_SPECIFIC_CAMERA := true

# Flags
COMMON_GLOBAL_CFLAGS += \
    -DCONFIG_WT88047_CAMERA \
    -DCAMERA_VENDOR_L_COMPAT
